spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: lb://CUSTOMER-SERVICE:8081
          predicates:
          - Path= /customers/**
        - id: r2
          uri: lb://INVENTORY-SERVICE:8082
          predicates:
          - Path= /products/**

# lb : load balancer
# CUSTOMER-SERVICE : service name
# INVENTORY-SERVICE : service name